CREATE TABLE IF NOT EXISTS players (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       player_id VARCHAR(255) NOT NULL,
    player_name VARCHAR(255),
    added_at DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS redemption_log (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              user_id VARCHAR(255) NOT NULL,
    player VARCHAR(255),
    code VARCHAR(255) NOT NULL,
    status ENUM(
                   'ALREADY_REDEEMED',
                   'EXPIRED',
                   'FAILED',
                   'INVALID_CODE',
                   'INVALID_PLAYER',
                   'PENDING',
                   'SERVER_BUSY',
                   'SUCCESS',
                   'UNKNOWN_ERROR'
               ) NOT NULL,
    attempt_number INT NOT NULL,
    error_message VARCHAR(255),
    attempted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    redeemed_at TIMESTAMP WITH TIME ZONE
                              );